apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: aircraft-api
  name: aircraft-api
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8082
  selector:
    io.kompose.service: aircraft-api
status:
  loadBalancer: {}

