apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: aircraft-api
  name: aircraft-api
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    io.kompose.service: aircraft-api
status:
  loadBalancer: {}