pipeline:
  build_docker_image:
    image: docker:stable-dind
    privileged: false
    when:
      branch: [master, develop]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./docker-build.sh egar-flight-api
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/$(SLACK_WEBHOOK)
    channel: builds
    when:
      status: [success, failure]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  deploy_docker_image:
    image: docker:stable-dind
    privileged: false
    when:
      branch: [master, develop]
    commands:
      - ./docker-deploy.sh egar-flight-api
